name: "Titlovi.com"
guid: "6e25df50-638e-4109-a50b-03c14fc93fdd"
imageUrl: "https://github.com/Titlovi/titlovi-jellyfin/blob/main/logo.png?raw=true"
version: "1.2.2.0"
targetAbi: "10.11.5.0"
framework: "net9.0"
overview: "get access to subtitles from titlovi.com directly in jellyfin."
description: >
  This plugin allows Jellyfin users to seamlessly access and download subtitles from Titlovi.com directly within the media server,
  instead of manually searching for subtitle files. You can browse and fetch them through Jellyfin’s interface,
  ensuring your movies and TV shows are always synced with high-quality, community-provided subtitles in multiple languages.
category: "Metadata"
owner: "maatko"
artifacts:
- "Refit.HttpClientFactory.dll"
- "Titlovi.Plugin.dll"
- "Titlovi.Api.dll"
- "FuzzySharp.dll"
- "Refit.dll"
changelog: >
  + jellyfin 10.11.* and upwards
  + fixed an issue where authentication was not processed correctly
  + fixed an issue where episode metadata was not matched correctly on an episode
  + proper searching on all search pages for subtitles
  + fixed an issue where some movies were not showing up do to imdb ids