---
name: "Titlovi.com"
guid: "6e25df50-638e-4109-a50b-03c14fc93fdd"
version: "1.0.0.0"
targetAbi: "10.10.7.0"
framework: "net8.0"
overview: "get access to subtitles from titlovi.com directly in jellyfin."
description: >
  This plugin allows Jellyfin users to seamlessly access and download subtitles from Titlovi.com directly within the media server,
  instead of manually searching for subtitle files. You can browse and fetch them through Jellyfin’s interface,
  ensuring your movies and TV shows are always synced with high-quality, community-provided subtitles in multiple languages.
category: "Metadata"
owner: "maatko"
artifacts:
- "Titlovi.Jellyfin.dll"
- "FuzzySharp.dll"
changelog: >
  Initial Release
