name: '🚀 Publish Plugin'

on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  call:
    uses: Kevinjil/jellyfin-plugin-repo-action@v0.4.3
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      repository: "maatko/jellyfin-titlovi"
