name: '🚀 Publish Plugin'

on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  publish-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout plugin repo
        uses: actions/checkout@v3
        with:
          repository: maatko/jellyfin-titlovi
          ref: gh-pages 
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Jellyfin plugin repo
        uses: Kevinjil/jellyfin-plugin-repo-action@v0.4.3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }} 
          repository: "maatko/jellyfin-titlovi"
          pagesBranch: "gh-pages"
