update-repo-manifest:
  needs: release
  runs-on: ubuntu-latest

  steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        persist-credentials: true

    - name: Download plugin asset from release
      uses: robinraju/release-downloader@v1
      with:
        repository: ${{ github.repository }}
        tag: ${{ github.event.release.tag_name }}
        fileName: "*.zip"
        out-file-path: ./artifacts

    - name: Update repository manifest
      uses: kevinjil/jellyfin-plugin-repo@v2
      with:
        artifact: ./artifacts/*.zip
        repository-manifest: ./manifest.json
        release-tag: ${{ github.event.release.tag_name }}
        release-url: ${{ github.event.release.html_url }}

    - name: Commit and push manifest.json
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add manifest.json
        git commit -m "Update manifest for ${{ github.event.release.tag_name }}"
        git push
